### ISSUE TITLE
Failing because of pop3

### ISSUE THREAD

**Issue by epicfaace** [intrigueio/intrigue-ident#50]
This is on the latest master (2.0.7):

```
 /app/intrigue-ident/lib/ident.rb:103:in `require_relative': cannot load such file -- /app/intrigue-ident/checks/pop3/base (LoadError)
        from /app/intrigue-ident/lib/ident.rb:103:in `<top (required)>'
        from ./util/ident.rb:2:in `require_relative'
        from ./util/ident.rb:2:in `<main>'
 1
```

**Comment by jcran** [comment]
Thanks for the report, fixed on main.

**Comment by epicfaace** [comment]
Thanks for the quick fix!
